{{- if and .Values.enabled .Values.services.celeryWorker.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}-celery-worker-scaler
  namespace: {{ .Values.services.celeryWorker.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ml-autoscaling.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: celery-worker-scaler
    ml-autoscaling/enabled: "true"
spec:
  scaleTargetRef:
    name: {{ .Values.services.celeryWorker.deployment }}
    kind: Deployment
  
  minReplicaCount: {{ .Values.services.celeryWorker.minReplicas }}
  maxReplicaCount: {{ .Values.services.celeryWorker.maxReplicas }}
  
  pollingInterval: 30
  cooldownPeriod: 60
  
  triggers:
  {{- if .Values.services.celeryWorker.triggers.rabbitmq.enabled }}
  - type: rabbitmq
    metadata:
      host: {{ .Values.services.celeryWorker.triggers.rabbitmq.host | default "amqp://user:pass@rabbitmq.default.svc.cluster.local:5672/%2f" }}
      queueName: {{ .Values.services.celeryWorker.triggers.rabbitmq.queueName }}
      queueLength: {{ .Values.services.celeryWorker.triggers.rabbitmq.queueLength | quote }}
      protocol: amqp
  {{- end }}
  
  {{- if .Values.services.celeryWorker.triggers.latency.enabled }}
  - type: prometheus
    metadata:
      serverAddress: {{ .Values.prometheus.serverAddress }}
      metricName: celery_task_duration_p95
      threshold: {{ .Values.services.celeryWorker.triggers.latency.targetValue | quote }}
      query: |
        histogram_quantile(0.95, 
          sum(rate(celery_task_duration_seconds_bucket[5m])) 
          by (le)
        )
  {{- end }}
  
  {{- if .Values.services.celeryWorker.triggers.errorRate.enabled }}
  - type: prometheus
    metadata:
      serverAddress: {{ .Values.prometheus.serverAddress }}
      metricName: celery_task_error_rate
      threshold: {{ .Values.services.celeryWorker.triggers.errorRate.threshold | quote }}
      query: |
        sum(rate(celery_task_failed_total[5m])) / 
        sum(rate(celery_task_total[5m]))
  {{- end }}
  
  advanced:
    behavior:
      scaleUp:
        stabilizationWindowSeconds: {{ .Values.services.celeryWorker.scaleUp.stabilizationWindowSeconds }}
        policies:
{{ toYaml .Values.services.celeryWorker.scaleUp.policies | indent 8 }}
        selectPolicy: {{ .Values.services.celeryWorker.scaleUp.selectPolicy }}
      scaleDown:
        stabilizationWindowSeconds: {{ .Values.services.celeryWorker.scaleDown.stabilizationWindowSeconds }}
        policies:
{{ toYaml .Values.services.celeryWorker.scaleDown.policies | indent 8 }}
        selectPolicy: {{ .Values.services.celeryWorker.scaleDown.selectPolicy }}
{{- end }}