artifact_uri: file:///Users/vitaliiserbyn/development/wt-a2-genai/unified_model_comparison/520432245793831702/22ac998defac430e88300bc65c1caa14/artifacts
end_time: 1755271999909
entry_point_name: ''
experiment_id: '520432245793831702'
lifecycle_stage: active
run_id: 22ac998defac430e88300bc65c1caa14
run_name: unified_test_DialoGPT-Medium_20250815_183316
source_name: ''
source_type: 4
source_version: ''
start_time: 1755271996520
status: 3
tags: []
user_id: vitaliiserbyn
