# ────────────────────────────────────────────────────────
#  values-dev.yaml  – local k3d overrides
# ────────────────────────────────────────────────────────
tag: local

image:
  repository: orchestrator
  tag: local

celeryWorker:
  image:
    repository: celery-worker
    tag: local

personaRuntime:
  image:
    repository: persona-runtime
    tag: local

rabbitmq:
  url: "amqp://user:pass@rabbitmq:5672/%2f"

# ───────── enable stub-stack services ─────────
postgres:
  enabled: true
  storage: 1Gi       # matches pvc spec

minio:
  enabled: true
  accessKey: "minio"
  secretKey: "minio123"
  storage: 1Gi       # small local disk

fakeThreads:
  enabled: true
  image:
    repository: fake-threads
    tag: local
  port: 9009
  pullSecret: ghcr-creds   # ← your personal GHCR PAT docker-login secret

postgres:
  enabled: true

threadsService:
  name: fake-threads
  port: 9009

rabbitmq:
  url: "amqp://user:pass@rabbitmq:5672/%2f"

# ───────── misc ─────────
replicaCount: 1
service:
  type: ClusterIP
  port: 8080
resources: {}
