# ────────────────────────────────────────────────────────
#  values-dev.yaml  – local k3d overrides
# ────────────────────────────────────────────────────────
tag: local

image:
  repository: orchestrator
  tag: local

celeryWorker:
  image:
    repository: celery-worker
    tag: local

personaRuntime:
  image:
    repository: persona-runtime
    tag: local

fakeThreads:
  image:
    repository: fake-threads
    tag: local
  port: 9009
  # pullSecret *not* needed for local images

postgres:
  enabled: true

threadsService:
  name: fake-threads
  port: 9009

rabbitmq:
  url: "amqp://user:pass@rabbitmq:5672/%2f"

replicaCount: 1
service:
  type: ClusterIP
  port: 8080
resources: {}
