# /chart/values-prod.yaml
replicaCount: 3
service:
  type: LoadBalancer

# Comment Monitoring - Production Optimized Configuration
orchestrator:
  resources:
    requests:
      memory: "768Mi"                  # Increased for comment processing
      cpu: "300m"
    limits:
      memory: "2Gi"                    # Higher limit for high-volume processing
      cpu: "1500m"
  
  commentMonitoring:
    enabled: true
    batchSize: 25                      # Larger batches for efficiency
    dedupCacheTTL: 7200               # Longer TTL for production
    processingTimeout: 45              # More time for complex processing
    maxRetries: 5                      # More retries for production
    rateLimitPerMinute: 200           # Higher rate limit for production
    
    metrics:
      enabled: true
      
    alerts:
      queueBacklogThreshold: 1000     # Higher threshold for production
      memoryThresholdGb: 1.5          # Alert before hitting limit
      cpuThreshold: 0.85              # Higher CPU threshold
      
    networkPolicy:
      enabled: true                   # Enable network security
      
    rbac:
      enabled: true                   # Enable RBAC
  
  serviceMonitor:
    enabled: true
    interval: "30s"
    scrapeTimeout: "10s"
  
  autoscaling:
    enabled: true
    minReplicas: 2                    # Minimum replicas for HA
    maxReplicas: 10                   # Allow scaling for high load
    targetCPUUtilization: 75
    targetMemoryUtilization: 80
    
    customMetrics:
      enabled: true                   # Enable queue-based scaling
      targetQueueLength: 75           # Scale when queue gets large
      
    scaleUp:
      stabilizationWindowSeconds: 45  # Faster scale-up for comment bursts
      percentPolicy: 100
      periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 600 # Slower scale-down for stability
      percentPolicy: 25
      periodSeconds: 60
  
  pdb:
    enabled: true
    minAvailable: 1                   # Ensure availability during updates

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
persistence:
  enabled: true
  size: 5Gi
  storageClass: gp3

# ───────── monitoring & observability ─────────
monitoring:
  prometheus:
    enabled: true
    url: http://prometheus:9090
    persistence:
      enabled: true
      size: 5Gi
      storageClass: gp3
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 512Mi
  grafana:
    enabled: true
    adminPassword: "{{ .Values.grafana.adminPassword | default \"changeme\" }}"
    plugins: "grafana-piechart-panel,grafana-polystat-panel"
    persistence:
      enabled: true
      size: 2Gi
      storageClass: gp3
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
    externalUrl: https://grafana.threads-agent.com
  alertmanager:
    enabled: true
    replicas: 2
    persistence:
      enabled: true
      size: 2Gi
      storageClass: gp3
    externalUrl: https://alerts.threads-agent.com
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    # Email configuration (production)
    smtp:
      smarthost: "{{ .Values.alerting.smtp.smarthost }}"
      from: "alerts@threads-agent.com"
      auth:
        username: "{{ .Values.alerting.smtp.username }}"
        password: "{{ .Values.alerting.smtp.password }}"
    # PagerDuty integration (production)
    pagerduty:
      enabled: true
      integrationKey: "{{ .Values.alerting.pagerduty.integrationKey }}"
    # Slack integration (production)
    slack:
      enabled: true
      apiUrl: "{{ .Values.alerting.slack.webhookUrl }}"
      warningsChannel: "#alerts-warnings"
      infrastructureChannel: "#alerts-infrastructure"
    # Email recipients (production)
    email:
      enabled: true
      from: "alerts@threads-agent.com"
      businessRecipients: "business@threads-agent.com,founders@threads-agent.com"
      infrastructureRecipients: "ops@threads-agent.com,engineering@threads-agent.com"
