# ────────────────────────────────────────────────
# values-dev.yaml  – local k3d overrides
# ────────────────────────────────────────────────
replicaCount: 1

image:
  repository: orchestrator            # ← local images, no GHCR prefix
  tag: local

celeryWorker:
  image:
    repository: celery-worker
    tag: local

personaRuntime:
  image:
    repository: persona-runtime
    tag: local

rabbitmq:
  url: "amqp://user:pass@rabbitmq:5672/%2f"

# ───────── stub-stack services ─────────
postgres:
  enabled: true
  auth:
    postgresPassword: pass
  storage: 1Gi                         # pvc size used in pvc.yaml / template

qdrant:
  enabled: true
  storage: 1Gi
  image:
    repository: qdrant/qdrant
    tag: v1.9.4

minio:
  enabled: true
  image:
    repository: bitnami/minio             # one place to change if you ever use a mirror
    tag: "2024"                           # dev-friendly multi-arch tag
  accessKey: minio
  secretKey: minio123
  storage: 1Gi

fakeThreads:
  enabled: true
  image:
    repository: fake-threads
    tag: local
  port: 9009
  pullSecret: ghcr-creds               # docker login secret (GHCR PAT)

threadsService:                        # used by orchestrator & worker envs
  name: fake-threads
  port: 9009

openai:
  enabled: true
  apiKey: "REPLACE_IN_RUNTIME"

# ───────── service for orchestrator itself ─────────
service:
  type: ClusterIP
  port: 8080

global:
  storageClass: local-path

resources: {}
