# ────────────────────────────────────────────────
# values-dev.yaml  – local k3d overrides
# ────────────────────────────────────────────────
replicaCount: 1

image:
  repository: orchestrator            # ← local images, no GHCR prefix
  tag: local

celeryWorker:
  image:
    repository: celery-worker
    tag: local

personaRuntime:
  image:
    repository: persona-runtime
    tag: local
  env:
    - name: HOOK_MODEL
      value: gpt-4o
    - name: BODY_MODEL
      value: gpt-3.5-turbo-0125
    # optional LoRA location
    - name: LORA_PATH
      value: /models/lora.safetensors
    - name: OPENAI_API_KEY   # forces stub even if the Secret still exists
      value: "test"

rabbitmq:
  url: "amqp://user:pass@rabbitmq:5672/%2f"

# ───────── stub-stack services ─────────
postgres:
  enabled: true
  auth:
    postgresPassword: pass
  storage: 1Gi                         # pvc size used in pvc.yaml / template

qdrant:
  enabled: true
  storage: 1Gi
  image:
    repository: qdrant/qdrant
    tag: v1.9.4

minio:
  enabled: true
  image:
    repository: bitnami/minio             # one place to change if you ever use a mirror
    tag: "2024"                           # dev-friendly multi-arch tag
  accessKey: minio
  secretKey: minio123
  storage: 1Gi

fakeThreads:
  enabled: true
  image:
    repository: fake-threads
    tag: local
  port: 9009
  pullSecret: ghcr-creds               # docker login secret (GHCR PAT)

threadsService:                        # used by orchestrator & worker envs
  name: fake-threads
  port: 9009

openai:
  enabled: false
  apiKey: "REPLACE_IN_RUNTIME"

# ───────── service for orchestrator itself ─────────
service:
  type: ClusterIP
  port: 8080

global:
  storageClass: local-path

resources: {}

# ───────── monitoring & observability ─────────
monitoring:
  prometheus:
    enabled: true
    url: http://prometheus:9090
    persistence:
      enabled: true
      size: 2Gi
      storageClass: local-path
  grafana:
    enabled: true
    adminPassword: admin123
    plugins: "grafana-piechart-panel"
    persistence:
      enabled: true
      size: 1Gi
      storageClass: local-path
