# chart/values-ci.yaml
# ─────────────────── CI overrides (local images) ───────────────────

image:
  repository: orchestrator   # <— matches docker build tag
  tag: "local"

celeryWorker:
  image:
    repository: celery-worker
    tag: "local"

personaRuntime:
  image:
    repository: persona-runtime
    tag: "local"
  env:
    - name: HOOK_MODEL
      value: gpt-4o
    - name: BODY_MODEL
      value: gpt-3.5-turbo-0125
    # optional LoRA location
    - name: LORA_PATH
      value: /models/lora.safetensors

fakeThreads:
  enabled: true
  image:
    repository: fake-threads
    tag: "local"
  port: 9009

threadsService:
  name: fake-threads
  port: 9009

# stub Postgres for e2e
postgres:
  enabled: true
  storage: 1Gi
  auth:
    # This password is written into the Bitnami-generated Secret
    #   Name:  <release>-postgresql
    #   Key :  postgres-password
    #
    # The migrations Job reads that same key, so *any* value works,
    # as long as it is present.
    postgresPassword: ci-pass

qdrant:
  enabled: true
  storage: 1Gi
  image:
    repository: qdrant/qdrant
    tag: v1.9.4

# MinIO not needed in CI yet
minio:
  enabled: false

openai:
  enabled: true
  apiKey: "REPLACE_IN_RUNTIME"

global:
  storageClass: local-path

service:
  type: ClusterIP
  port: 8080
