# CI values with probes disabled for debugging
# Copy all values from values-ci-fast.yaml and override fake-threads probes

# Use local images (already in values-ci.yaml)
image:
  repository: docker.io/library/orchestrator
  tag: "local"
  pullPolicy: IfNotPresent  # Changed from Never for CI compatibility

personaRuntime:
  enabled: true
  replicas: 1  # Minimal replicas for CI
  image:
    repository: docker.io/library/persona-runtime
    tag: "local"
    pullPolicy: IfNotPresent  # Changed from Never for CI compatibility
  resources:
    requests:
      memory: "128Mi"  # Conservative memory for LLM service
      cpu: "100m"      # More CPU for AI processing
    limits:
      memory: "256Mi"  # Adequate limits
      cpu: "300m"

# Conservative fake-threads config with NO PROBES
fakeThreads:
  enabled: true
  image:
    repository: docker.io/library/fake-threads
    tag: "local" 
    pullPolicy: IfNotPresent  # Changed from Never for CI compatibility
  port: 9009
  replicas: 1
  resources:
    requests:
      memory: "32Mi"   # Minimal for CI
      cpu: "20m"       # Minimal CPU
    limits:
      memory: "128Mi"  # Conservative limits
      cpu: "200m"
  # PROBES DISABLED FOR DEBUGGING
  readinessProbe: false
  livenessProbe: false
  startupProbe: false

# Minimal PostgreSQL for CI
postgres:
  enabled: true
  storage: 500Mi  # Minimal storage
  auth:
    postgresPassword: "postgres"  # Simple password for CI
  resources:
    requests:
      memory: "64Mi"
      cpu: "25m"
    limits:
      memory: "128Mi"
      cpu: "100m"

# Minimal RabbitMQ
rabbitmq:
  enabled: true
  resources:
    requests:
      memory: "64Mi"
      cpu: "25m"
    limits:
      memory: "128Mi"
      cpu: "100m"

# Enable celery worker with optimized settings for CI
celeryWorker:
  enabled: true
  replicas: 1
  image:
    repository: docker.io/library/celery-worker
    tag: "local"
    pullPolicy: IfNotPresent  # Changed from Never for CI compatibility
  resources:
    requests:
      memory: "128Mi"  # Reasonable for 2 worker processes
      cpu: "50m"       # Minimal CPU for CI
    limits:
      memory: "256Mi"  # Should be enough with concurrency=2
      cpu: "200m"
  # Disable health checks in CI - metrics port not reliably available
  livenessProbe: false
  readinessProbe: false

# Disable all optional services
viralEngine:
  enabled: false
achievementCollector:
  enabled: false
conversationEngine:
  enabled: false
revenue:
  enabled: false
viralMetrics:
  enabled: false
mlflow:
  performanceOptimization:
    enabled: false

# Minimal Qdrant
qdrant:
  enabled: true
  image:
    repository: qdrant/qdrant
    tag: "v1.9.4"  # Match the version we import in CI
  resources:
    requests:
      memory: "64Mi"
      cpu: "25m"
    limits:
      memory: "128Mi"
      cpu: "100m"

# Skip monitoring entirely
monitoring:
  prometheus:
    enabled: false
  grafana:
    enabled: false
  alertmanager:
    enabled: false

# Global deployment optimizations
global:
  # Reduced resource requests across all services
  resources:
    requests:
      memory: "32Mi"
      cpu: "10m"
    limits:
      memory: "128Mi" 
      cpu: "100m"