artifact_uri: file:///Users/vitaliiserbyn/development/wt-a2-genai/enhanced_business_mlflow/877356310361965032/ca992c4ed09d4f95b263e099f7b19aea/artifacts
end_time: 1755274495365
entry_point_name: ''
experiment_id: '877356310361965032'
lifecycle_stage: active
run_id: ca992c4ed09d4f95b263e099f7b19aea
run_name: enhanced_DialoGPT-Medium_20250815_191452
source_name: ''
source_type: 4
source_version: ''
start_time: 1755274492468
status: 3
tags: []
user_id: vitaliiserbyn
