apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus
  namespace: default
  labels:
    app: event-bus
    component: infrastructure
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
      - name: event-bus
        image: event-bus:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: RABBITMQ_URL
          value: "amqp://user:pass@rabbitmq:5672/"
        - name: DATABASE_URL
          value: "postgresql://postgres:pass@postgres:5432/events"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: event-bus
  namespace: default
  labels:
    app: event-bus
spec:
  selector:
    app: event-bus
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  type: ClusterIP