artifact_location: file:///Users/vitaliiserbyn/development/wt-a2-genai/enhanced_business_mlflow/148605544799192488
creation_time: 1755363397582
experiment_id: '148605544799192488'
last_update_time: 1755363397582
lifecycle_stage: active
name: rigorous_statistical_validation
