artifact_uri: file:///Users/vitaliiserbyn/development/wt-a2-genai/enhanced_business_mlflow/877356310361965032/99cc22b0911d4c699bbd6f7e5fc65ff3/artifacts
end_time: 1755275105254
entry_point_name: ''
experiment_id: '877356310361965032'
lifecycle_stage: active
run_id: 99cc22b0911d4c699bbd6f7e5fc65ff3
run_name: premium_dialogpt_large_20250815_192436
source_name: ''
source_type: 4
source_version: ''
start_time: 1755275076831
status: 3
tags: []
user_id: vitaliiserbyn
