# .pre-commit-config.yaml  (place at repo root)
repos:
  # ➊ Ruff — lint + many autofixes (I rules ignored; handled by isort)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4       # keep in sync with requirements-dev.txt
    hooks:
      - id: ruff
        args: [--fix, --extend-ignore=I]
        pass_filenames: false      # fastest mode

  # ➋ isort — canonical import order
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  # ➌ Black — final formatter (diff-only)
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: [--check]

  # ➍ mypy — static type check
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        pass_filenames: false
        args:
          - --config-file
          - mypy.ini
          - .
        additional_dependencies:
          - numpy
          - types-requests
          - qdrant-client
          - pydantic>=2.7
          - fastapi>=0.111
          - celery>=5.4
          - typer>=0.12
          - "sqlalchemy>=2.0"
          - greenlet>=3.0
          - pytest>=8.4

