# Pre-commit hooks for fast local feedback
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  # AI Development Acceleration Hooks
  - repo: local
    hooks:
      - id: ai-quality-gate
        name: AI Quality Gate (Fast)
        entry: ./scripts/ai-dev-acceleration.sh quality
        language: script
        pass_filenames: false
        stages: [pre-push]
        
      - id: ai-context-update
        name: Update AI Context
        entry: ./scripts/ai-dev-acceleration.sh context
        language: script
        pass_filenames: false
        stages: [post-commit]
        
      - id: smart-test
        name: Smart Testing
        entry: ./scripts/ai-dev-acceleration.sh test
        language: script
        pass_filenames: false
        stages: [pre-commit]