artifact_location: file:///Users/vitaliiserbyn/development/wt-a2-genai/improved_testing_demo/868571182362759893
creation_time: 1755356218928
experiment_id: '868571182362759893'
last_update_time: 1755356218928
lifecycle_stage: active
name: improved_methodology_demo
