artifact_uri: file:///Users/vitaliiserbyn/development/wt-a2-genai/enhanced_business_mlflow/877356310361965032/f6b2199db1c64c3f84febd06fa8c9e99/artifacts
end_time: 1755338854369
entry_point_name: ''
experiment_id: '877356310361965032'
lifecycle_stage: active
run_id: f6b2199db1c64c3f84febd06fa8c9e99
run_name: business_specialist_godel_20250816_130415
source_name: ''
source_type: 4
source_version: ''
start_time: 1755338655788
status: 3
tags: []
user_id: vitaliiserbyn
