# chart/templates/celery-worker.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: "{{ tpl .Values.celeryWorker.image.repository $ }}:{{ tpl .Values.celeryWorker.image.tag $ }}"
          env:
            - name: RABBITMQ_URL
              value: {{ .Values.rabbitmq.url }}
            - name: CELERY_BROKER_URL
              value: {{ .Values.rabbitmq.url }}
            - name: THREADS_BASE_URL
              value: "http://{{ .Values.threadsService.name }}:{{ .Values.threadsService.port }}"
          resources: {}
