# chart/templates/celery-worker.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: "{{ tpl .Values.celeryWorker.image.repository $ }}:{{ tpl .Values.celeryWorker.image.tag $ }}"
          imagePullPolicy: {{ .Values.celeryWorker.image.pullPolicy | default "IfNotPresent" }}
          env:
            - name: RABBITMQ_URL
              value: {{ .Values.rabbitmq.url }}
            - name: CELERY_BROKER_URL
              value: {{ .Values.rabbitmq.url }}
            - name: THREADS_BASE_URL
              {{- if .Values.threadsAdaptor.enabled }}
              value: "http://threads-adaptor:8080"
              {{- else }}
              value: "http://{{ .Values.threadsService.name }}:{{ .Values.threadsService.port }}"
              {{- end }}
            - name: POSTGRES_DSN
              value: "postgresql://{{ .Values.postgres.auth.username }}:{{ .Values.postgres.auth.postgresPassword }}@postgres:5432/{{ .Values.postgres.auth.database }}"
            - name: DATABASE_URL
              value: "postgresql://{{ .Values.postgres.auth.username }}:{{ .Values.postgres.auth.postgresPassword }}@postgres:5432/{{ .Values.postgres.auth.database }}"
            - name: QDRANT_URL
              value: "http://qdrant:6333"
          envFrom:
            - secretRef:
                name: openai-secret

          ports:
            - name: metrics
              containerPort: 9090

          resources: {}
