{{- if .Values.conversationEngine.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversation-engine
  labels:
    app: conversation-engine
    {{- include "threads.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.conversationEngine.replicas }}
  selector:
    matchLabels:
      app: conversation-engine
  template:
    metadata:
      labels:
        app: conversation-engine
        {{- include "threads.labels" . | nindent 8 }}
    spec:
      containers:
      - name: conversation-engine
        image: "{{ .Values.conversationEngine.image.repository }}:{{ .Values.conversationEngine.image.tag }}"
        imagePullPolicy: {{ .Values.conversationEngine.image.pullPolicy }}
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:{{ .Values.postgres.auth.postgresPassword }}@postgres:5432/threads"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: OPENAI_API_KEY
        - name: CONVERSATION_MODEL
          value: {{ .Values.conversationEngine.model | default "gpt-4o" | quote }}
        - name: CONVERSATION_TEMPERATURE
          value: {{ .Values.conversationEngine.temperature | default "0.7" | quote }}
        - name: CONVERSATION_CACHE_TTL
          value: {{ .Values.conversationEngine.cacheTTL | default "3600" | quote }}
        {{- if .Values.conversationEngine.extraEnv }}
        {{- toYaml .Values.conversationEngine.extraEnv | nindent 8 }}
        {{- end }}
        resources:
          {{- toYaml .Values.conversationEngine.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: conversation-engine
  labels:
    app: conversation-engine
    {{- include "threads.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: conversation-engine
---
{{- if .Values.conversationEngine.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: conversation-engine-hpa
  labels:
    app: conversation-engine
    {{- include "threads.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: conversation-engine
  minReplicas: {{ .Values.conversationEngine.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.conversationEngine.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.conversationEngine.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.conversationEngine.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }}
---
{{- if .Values.conversationEngine.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: conversation-engine-pdb
  labels:
    app: conversation-engine
    {{- include "threads.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.conversationEngine.pdb.minAvailable }}
  selector:
    matchLabels:
      app: conversation-engine
{{- end }}
---
{{- if .Values.conversationEngine.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: conversation-engine
  labels:
    app: conversation-engine
    {{- include "threads.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: conversation-engine
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
{{- end }}
{{- end }}