# chart/templates/postgres.yaml
{{- /* ----------------------------------------------------------------
      Postgres (dev only)
      Renders only when .Values.postgres.enabled == true
------------------------------------------------------------------- */}}

{{- if .Values.postgres.enabled }}

# 1️⃣  password secret – keep it simple in dev
apiVersion: v1
kind: Secret
metadata:
  name: threads-postgresql
type: Opaque
stringData:
  POSTGRES_PASSWORD: "{{ .Values.postgres.auth.postgresPassword }}"

---

# 2️⃣  statefulset
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      serviceAccountName: postgres-sa
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: threads-postgresql, key: POSTGRES_PASSWORD } }
            - name: POSTGRES_DB
              value: {{ .Values.postgres.auth.database | default "threads_agent" }}  # Automatically create the database
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          resources:
            {{- if .Values.postgres.resources }}
            requests:
              memory: {{ .Values.postgres.resources.requests.memory | default "64Mi" }}
              cpu: {{ .Values.postgres.resources.requests.cpu | default "25m" }}
            limits:
              memory: {{ .Values.postgres.resources.limits.memory | default "128Mi" }}
              cpu: {{ .Values.postgres.resources.limits.cpu | default "100m" }}
            {{- else }}
            requests:
              memory: "64Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "100m"
            {{- end }}
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        storageClassName: local-path     # <— works out-of-the-box with k3d
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: "{{ .Values.postgres.storage | default "1Gi" }}"

---

# 3️⃣  Cluster-IP service
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432

---

# 4️⃣  minimal service-account (Bitnami image wants one)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-sa

{{- end }}
