{{- if .Values.revenue.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: revenue
  labels:
    {{- include "threads.labels" . | nindent 4 }}
    app.kubernetes.io/component: revenue
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  - port: 9090
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app: revenue
{{- end }}