# chart/templates/secret-openai.yaml
{{- if .Values.openai.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
type: Opaque
stringData:
  OPENAI_API_KEY: {{ .Values.openai.apiKey | quote }}
{{- end }}
