{{- if .Values.threadsAdaptor.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: threads-api-credentials
type: Opaque
stringData:
  THREADS_APP_ID: {{ .Values.threadsAdaptor.credentials.appId | quote }}
  THREADS_APP_SECRET: {{ .Values.threadsAdaptor.credentials.appSecret | quote }}
  THREADS_ACCESS_TOKEN: {{ .Values.threadsAdaptor.credentials.accessToken | quote }}
  THREADS_USER_ID: {{ .Values.threadsAdaptor.credentials.userId | quote }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: threads-adaptor
  labels:
    app: threads-adaptor
spec:
  replicas: {{ .Values.threadsAdaptor.replicas | default 1 }}
  selector:
    matchLabels:
      app: threads-adaptor
  template:
    metadata:
      labels:
        app: threads-adaptor
    spec:
      containers:
      - name: threads-adaptor
        image: "{{ .Values.threadsAdaptor.image.repository }}:{{ .Values.threadsAdaptor.image.tag }}"
        imagePullPolicy: {{ .Values.threadsAdaptor.image.pullPolicy }}
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: DATABASE_URL
          value: "postgresql://{{ .Values.postgres.auth.username }}:{{ .Values.postgres.auth.password }}@postgres:5432/{{ .Values.postgres.auth.database }}"
        - name: THREADS_RATE
          value: {{ .Values.threadsAdaptor.rateLimit | default 20 | quote }}
        envFrom:
        - secretRef:
            name: threads-api-credentials
        {{- with .Values.threadsAdaptor.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        resources:
          {{- toYaml .Values.threadsAdaptor.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: threads-adaptor
  labels:
    app: threads-adaptor
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  - port: 9090
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app: threads-adaptor
{{- end }}