{{- if .Values.viralMetrics.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "threads-agent.fullname" . }}-viral-metrics
  labels:
    {{- include "threads-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: viral-metrics
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "threads-agent.fullname" . }}-viral-metrics
  minReplicas: {{ .Values.viralMetrics.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.viralMetrics.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: viral_metrics_collection_latency_seconds
      target:
        type: AverageValue
        averageValue: "45"  # Scale up if average latency > 45s (75% of 60s SLA)
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
{{- end }}