apiVersion: 1

# FinOps Executive Dashboard Alert Rules
# Critical business and operational alerts for executive monitoring

groups:
  - name: finops-executive-alerts
    interval: 30s
    rules:
      # ROI Performance Alerts
      - alert: ROI_Below_Target
        expr: finops_roi_percentage < 300
        for: 5m
        labels:
          severity: warning
          category: business
          dashboard: executive-summary
        annotations:
          summary: "ROI below target threshold"
          description: "Current ROI ({{ $value }}%) is below the 300% target threshold"
          impact: "Revenue and profitability targets at risk"
          action: "Review cost optimization opportunities and revenue strategies"

      - alert: ROI_Critical_Drop
        expr: finops_roi_percentage < 200
        for: 2m
        labels:
          severity: critical
          category: business
          dashboard: executive-summary
        annotations:
          summary: "Critical ROI drop detected"
          description: "ROI has dropped to {{ $value }}%, immediate attention required"
          impact: "Significant revenue impact, business targets in jeopardy"
          action: "Emergency cost review and optimization required"

      # Revenue Performance Alerts
      - alert: Revenue_Target_Miss
        expr: finops_total_revenue < 16000  # 80% of $20k target
        for: 10m
        labels:
          severity: warning
          category: business
          dashboard: executive-summary
        annotations:
          summary: "Monthly revenue target at risk"
          description: "Current revenue ${{ $value }} is below 80% of $20k monthly target"
          impact: "Monthly revenue targets may not be achieved"
          action: "Review content performance and engagement strategies"

      - alert: Revenue_Growth_Stagnant
        expr: finops_growth_rate < 5
        for: 15m
        labels:
          severity: warning
          category: business
          dashboard: revenue-attribution
        annotations:
          summary: "Revenue growth below expectations"
          description: "Growth rate of {{ $value }}% is below 5% target"
          impact: "Long-term revenue projections at risk"
          action: "Analyze top-performing content patterns and scale successful strategies"

      # Cost Management Alerts
      - alert: Budget_Utilization_High
        expr: finops_budget_utilization_percentage > 90
        for: 5m
        labels:
          severity: warning
          category: cost
          dashboard: cost-optimization
        annotations:
          summary: "Budget utilization approaching limit"
          description: "Current budget utilization at {{ $value }}%"
          impact: "Risk of budget overrun this month"
          action: "Implement immediate cost controls and review spending"

      - alert: Budget_Exceeded
        expr: finops_budget_utilization_percentage > 100
        for: 1m
        labels:
          severity: critical
          category: cost
          dashboard: cost-optimization
        annotations:
          summary: "Budget exceeded"
          description: "Budget utilization at {{ $value }}%, over allocated budget"
          impact: "Budget overrun confirmed, immediate cost reduction required"
          action: "Emergency spending freeze and cost optimization"

      - alert: Cost_Per_Engagement_High
        expr: finops_cost_per_engagement > 0.05
        for: 10m
        labels:
          severity: warning
          category: efficiency
          dashboard: cost-optimization
        annotations:
          summary: "Cost per engagement exceeding targets"
          description: "Cost per engagement at ${{ $value }}, above $0.05 target"
          impact: "Efficiency metrics below target, ROI impact"
          action: "Review content optimization and model usage efficiency"

      # Engagement Performance Alerts
      - alert: Engagement_Rate_Low
        expr: finops_engagement_rate * 100 < 4
        for: 15m
        labels:
          severity: warning
          category: performance
          dashboard: executive-summary
        annotations:
          summary: "Engagement rate below minimum threshold"
          description: "Current engagement rate {{ $value }}% is below 4% minimum"
          impact: "Content performance declining, revenue impact likely"
          action: "Review content strategy and engagement optimization"

      - alert: Engagement_Rate_Critical
        expr: finops_engagement_rate * 100 < 2
        for: 5m
        labels:
          severity: critical
          category: performance
          dashboard: executive-summary
        annotations:
          summary: "Critical engagement rate drop"
          description: "Engagement rate critically low at {{ $value }}%"
          impact: "Severe performance degradation, immediate intervention required"
          action: "Emergency content strategy review and system diagnostics"

      # System Health Alerts
      - alert: System_Health_Degraded
        expr: finops_system_health_score < 0.9
        for: 5m
        labels:
          severity: warning
          category: operational
          dashboard: realtime-operations
        annotations:
          summary: "System health degraded"
          description: "System health score at {{ $value }}, below 90% threshold"
          impact: "Operational efficiency reduced, potential service impact"
          action: "Review system performance and resource utilization"

      - alert: Service_Down
        expr: finops_service_health < 0.5
        for: 1m
        labels:
          severity: critical
          category: operational
          dashboard: realtime-operations
        annotations:
          summary: "Critical service failure"
          description: "Service health critically low at {{ $value }}"
          impact: "Service outage detected, business operations impacted"
          action: "Immediate incident response and system restoration"

      # Attribution Accuracy Alerts
      - alert: Attribution_Accuracy_Low
        expr: finops_attribution_accuracy < 0.9
        for: 10m
        labels:
          severity: warning
          category: data_quality
          dashboard: revenue-attribution
        annotations:
          summary: "Revenue attribution accuracy below target"
          description: "Attribution accuracy at {{ $value }}, below 90% target"
          impact: "Revenue tracking reliability compromised"
          action: "Review data collection and attribution methodologies"

      # Optimization Opportunity Alerts
      - alert: High_Savings_Opportunity
        expr: finops_potential_savings_monthly > 1000
        for: 5m
        labels:
          severity: info
          category: optimization
          dashboard: cost-optimization
        annotations:
          summary: "Significant cost savings opportunity identified"
          description: "Potential monthly savings of ${{ $value }} detected"
          impact: "Opportunity to improve ROI and reduce costs"
          action: "Review and implement optimization recommendations"

      # Performance Regression Alerts
      - alert: Content_Performance_Decline
        expr: rate(finops_content_performance_score[1h]) < -0.1
        for: 15m
        labels:
          severity: warning
          category: performance
          dashboard: revenue-attribution
        annotations:
          summary: "Content performance declining"
          description: "Content performance score declining at {{ $value }} per hour"
          impact: "Engagement and revenue metrics may be affected"
          action: "Analyze recent content changes and performance patterns"

      # Real-time Operational Alerts
      - alert: High_Error_Rate
        expr: rate(finops_api_errors_total[5m]) / rate(finops_api_requests_total[5m]) * 100 > 5
        for: 2m
        labels:
          severity: critical
          category: operational
          dashboard: realtime-operations
        annotations:
          summary: "High API error rate detected"
          description: "API error rate at {{ $value }}%, above 5% threshold"
          impact: "Service reliability compromised, user experience affected"
          action: "Investigate errors and implement fixes immediately"

      - alert: Queue_Backlog_High
        expr: finops_queue_depth > 100
        for: 5m
        labels:
          severity: warning
          category: operational
          dashboard: realtime-operations
        annotations:
          summary: "Processing queue backlog high"
          description: "Queue depth at {{ $value }} items, above normal levels"
          impact: "Processing delays, potential service degradation"
          action: "Scale processing capacity or optimize queue handling"

# Alert routing and notification rules
route:
  group_by: ['alertname', 'severity', 'category']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default-receiver'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 5m
    
    - match:
        category: business
      receiver: 'executive-alerts'
      repeat_interval: 1h
    
    - match:
        category: operational
      receiver: 'ops-team-alerts'
      repeat_interval: 15m

# Notification receivers
receivers:
  - name: 'default-receiver'
    webhook_configs:
      - url: 'http://alertmanager-webhook:9093/webhook'
        send_resolved: true

  - name: 'critical-alerts'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#finops-critical'
        title: 'FinOps Critical Alert'
        text: 'Critical Issue: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        send_resolved: true
    
    pagerduty_configs:
      - service_key: 'YOUR_PAGERDUTY_SERVICE_KEY'
        description: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

  - name: 'executive-alerts'
    email_configs:
      - to: 'executives@threadsagent.com'
        subject: 'FinOps Executive Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        body: |
          Executive Alert Summary:
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Impact: {{ .Annotations.impact }}
          Recommended Action: {{ .Annotations.action }}
          
          Dashboard: {{ .Labels.dashboard }}
          Severity: {{ .Labels.severity }}
          {{ end }}

  - name: 'ops-team-alerts'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#finops-ops'
        title: 'FinOps Operations Alert'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'