artifact_location: file:///Users/vitaliiserbyn/development/wt-a2-genai/business_mlruns/737619720059296252
creation_time: 1755267160386
experiment_id: '737619720059296252'
last_update_time: 1755267160386
lifecycle_stage: active
name: solopreneur_model_analysis
