artifact_uri: file:///Users/vitaliiserbyn/development/wt-a2-genai/enhanced_business_mlflow/148605544799192488/c1b48a6e10ac47a0adce4d5e3168e06c/artifacts
end_time: 1755363431973
entry_point_name: ''
experiment_id: '148605544799192488'
lifecycle_stage: active
run_id: c1b48a6e10ac47a0adce4d5e3168e06c
run_name: bloom_560m_rigorous_rigorous_20250816_195637
source_name: ''
source_type: 4
source_version: ''
start_time: 1755363397646
status: 3
tags: []
user_id: vitaliiserbyn
