artifact_location: file:///Users/vitaliiserbyn/development/wt-a2-genai/unified_model_comparison/520432245793831702
creation_time: 1755271932358
experiment_id: '520432245793831702'
last_update_time: 1755271932358
lifecycle_stage: active
name: unified_business_model_comparison
