apiVersion: v1
kind: Namespace
metadata:
  name: chaos-engineering
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-engineering
  namespace: chaos-engineering
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaos-engineering
  template:
    metadata:
      labels:
        app: chaos-engineering
    spec:
      containers:
      - name: chaos-engineering
        image: chaos-engineering:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: LOG_LEVEL
          value: "INFO"
        - name: SAFETY_THRESHOLD
          value: "0.8"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: chaos-engineering
  namespace: chaos-engineering
spec:
  selector:
    app: chaos-engineering
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP