apiVersion: v2
name: ml-autoscaling
description: ML Infrastructure Auto-scaling with KEDA for threads-agent
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - ml
  - autoscaling
  - keda
  - kubernetes
  - predictive-scaling

maintainers:
  - name: threads-agent-team
    email: team@threads-agent.com

dependencies:
  - name: keda
    version: 2.13.*
    repository: https://kedacore.github.io/charts
    condition: keda.enabled

annotations:
  # MLOPS-008 Implementation
  feature: "ML Infrastructure Auto-scaling"
  epic: "MLOPS-008"