artifact_uri: file:///Users/vitaliiserbyn/development/wt-a2-genai/enhanced_business_mlflow/877356310361965032/c576e5b840c94d5c8113d711836f4a73/artifacts
end_time: null
entry_point_name: ''
experiment_id: '877356310361965032'
lifecycle_stage: active
run_id: c576e5b840c94d5c8113d711836f4a73
run_name: quality_leader_opt_2_7b_20250816_115933
source_name: ''
source_type: 4
source_version: ''
start_time: 1755334773097
status: 1
tags: []
user_id: vitaliiserbyn
