artifact_uri: file:///Users/vitaliiserbyn/development/wt-a2-genai/enhanced_business_mlflow/877356310361965032/71e522880d0d451690cfbad44be9aff7/artifacts
end_time: null
entry_point_name: ''
experiment_id: '877356310361965032'
lifecycle_stage: active
run_id: 71e522880d0d451690cfbad44be9aff7
run_name: champion_bloom_3b_20250816_125001
source_name: ''
source_type: 4
source_version: ''
start_time: 1755337801486
status: 1
tags: []
user_id: vitaliiserbyn
