artifact_location: file:///Users/vitaliiserbyn/development/wt-a2-genai/improved_testing_demo/0
creation_time: 1755356218925
experiment_id: '0'
last_update_time: 1755356218925
lifecycle_stage: active
name: Default
