artifact_location: file:///Users/vitaliiserbyn/development/wt-a2-genai/enterprise_grade_mlflow/850285565205111919
creation_time: 1755355596620
experiment_id: '850285565205111919'
last_update_time: 1755355596620
lifecycle_stage: active
name: enterprise_model_evaluation
