artifact_uri: file:///Users/vitaliiserbyn/development/wt-a2-genai/enhanced_business_mlflow/148605544799192488/063872cb0e214e719181ee610cb38a4b/artifacts
end_time: null
entry_point_name: ''
experiment_id: '148605544799192488'
lifecycle_stage: active
run_id: 063872cb0e214e719181ee610cb38a4b
run_name: CRITICAL_opt_2_7b_validation_20250817_030725
source_name: ''
source_type: 4
source_version: ''
start_time: 1755389245204
status: 1
tags: []
user_id: vitaliiserbyn
