artifact_uri: file:///Users/vitaliiserbyn/development/wt-a2-genai/enhanced_business_mlflow/148605544799192488/952b803542ff42bfb7ae90bfabefd6cf/artifacts
end_time: 1755430956103
entry_point_name: ''
experiment_id: '148605544799192488'
lifecycle_stage: active
run_id: 952b803542ff42bfb7ae90bfabefd6cf
run_name: BULLETPROOF_opt_2_7b_20250817_144136
source_name: ''
source_type: 4
source_version: ''
start_time: 1755430896589
status: 3
tags: []
user_id: vitaliiserbyn
