id: "epic_demo_1753228808"
name: "Demo: Build a mobile app for food delivery"
description: "AI-generated demo epic based on: Build a mobile app for food delivery"
complexity: "medium"
created: "2025-07-23T03:00:08+0300"
status: "planning"
ai_generated: true
demo_mode: true

# Epic Analysis
estimated_effort: "4 weeks"
risk_level: "medium"
business_value: "Demonstrates AI planning capabilities"

# Demo Features
features:
  - id: "feat_epic_demo_1753228808_001"
    name: "Core Implementation"
    effort: "large"
    priority: "high"
  - id: "feat_epic_demo_1753228808_002"
    name: "Testing & Quality"
    effort: "medium"
    priority: "high"
  - id: "feat_epic_demo_1753228808_003"
    name: "Documentation"
    effort: "small"
    priority: "medium"

# Milestones
milestones:
  - name: "Planning Complete"
    target_date: ""
    criteria: ["Requirements clarified", "Architecture approved"]
  - name: "MVP Ready"
    target_date: ""
    criteria: ["Core functionality working", "Basic tests passing"]

# Automation Configuration
automation:
  project_board: "local"
  branch_prefix: "demo-epic"
  ci_pipeline: "full"
