id: "epic_1755034797"
name: "Deployment of vLLM service and GenAI Engineer portfolio optimization"
description: "Deploy vLLM service locally using Llama-3.1-8B on MacBook M4 Max, implement RAG pipeline with Qdrant, and optimize costs. Also, create a hybrid local+cloud architecture for GenAI Engineer portfolio."
complexity: "large"
created: "2025-08-13T00:39:57+0300"
status: "planning"
lifecycle_stage: "inception"
ai_generated: true

# Epic Analysis
estimated_effort: "6 weeks"
risk_level: "medium"
business_value: "Reducing costs by 60% vs OpenAI API and enhancing GenAI Engineer's portfolio with a hybrid architecture."
technical_approach: |
  Utilizing existing MacBook M4 Max for local deployment, implementing RAG pipeline with Qdrant, and leveraging cost optimization methodologies.

# Risks
risks:
  - Potential compatibility issues with MacBook M4 Max
  - Unforeseen costs in implementing cost optimization dashboard

# Features (generated below)
features: []

# Milestones
milestones:
  - name: "Local Deployment Complete"
    target_date: "2025-08-13"
    criteria:
  - name: "null"
    target_date: "2025-08-27"
    criteria:
  - name: "null"
    target_date: "2025-08-13"
    criteria:
  - name: ""
    target_date: "2025-08-13"
    criteria:
  - name: ""
    target_date: "2025-08-13"
    criteria:
  - name: "RAG pipeline Complete"
    target_date: "2025-08-13"
    criteria:
  - name: "null"
    target_date: "2025-09-10"
    criteria:
  - name: "null"
    target_date: "2025-08-13"
    criteria:
  - name: ""
    target_date: "2025-08-13"
    criteria:
  - name: ""
    target_date: "2025-08-13"
    criteria:

# Success Metrics
metrics:
  - name: "Deployment Success"
    target: "null"
    measurement: "null"
  - name: "null"
    target: "Successful local deployment of vLLM service"
    measurement: "null"
  - name: "null"
    target: "null"
    measurement: "Check system logs and user access"
  - name: "RAG pipeline Efficiency"
    target: "null"
    measurement: "null"
  - name: "null"
    target: "RAG pipeline implemented without errors"
    measurement: "null"
  - name: "null"
    target: "null"
    measurement: "Monitor system performance and error logs"

# Automation Configuration
automation:
  project_board: "local"
  branch_prefix: "deployment-of-vllm-s"
  ci_pipeline: "full"
  notifications:
    - channel: "development"
      events: ["milestone_reached", "blocker_detected"]
  - id: "feat_epic_1755034797_07181"
    name: "Local Deployment of vLLM service"
    effort: "null"
    priority: "null"
  - id: "feat_epic_1755034797_24445"
    name: "null"
    effort: "null"
    priority: "null"
  - id: "feat_epic_1755034797_09849"
    name: "null"
    effort: "medium"
    priority: "null"
  - id: "feat_epic_1755034797_10274"
    name: "null"
    effort: "null"
    priority: "high"
  - id: "feat_epic_1755034797_10700"
    name: "null"
    effort: "null"
    priority: "null"
  - id: "feat_epic_1755034797_14759"
    name: "null"
    effort: "null"
    priority: "null"
  - id: "feat_epic_1755034797_18819"
    name: "null"
    effort: "null"
    priority: "null"
  - id: "feat_epic_1755034797_03315"
    name: ""
    effort: ""
    priority: ""
  - id: "feat_epic_1755034797_20578"
    name: ""
    effort: ""
    priority: ""
  - id: "feat_epic_1755034797_23730"
    name: "null"
    effort: "null"
    priority: "null"
  - id: "feat_epic_1755034797_08225"
    name: ""
    effort: ""
    priority: ""
  - id: "feat_epic_1755034797_26398"
    name: "null"
    effort: "null"
    priority: "null"
  - id: "feat_epic_1755034797_13619"
    name: "null"
    effort: "null"
    priority: "null"
  - id: "feat_epic_1755034797_32700"
    name: "null"
    effort: "null"
    priority: "null"
  - id: "feat_epic_1755034797_01266"
    name: ""
    effort: ""
    priority: ""
  - id: "feat_epic_1755034797_18529"
    name: "null"
    effort: "null"
    priority: "null"
  - id: "feat_epic_1755034797_18955"
    name: "null"
    effort: "null"
    priority: "null"
  - id: "feat_epic_1755034797_20289"
    name: "null"
    effort: "null"
    priority: "null"
  - id: "feat_epic_1755034797_20714"
    name: "RAG pipeline with Qdrant"
    effort: "null"
    priority: "null"
  - id: "feat_epic_1755034797_21139"
    name: "null"
    effort: "null"
    priority: "null"
  - id: "feat_epic_1755034797_21565"
    name: "null"
    effort: "large"
    priority: "null"
  - id: "feat_epic_1755034797_21990"
    name: "null"
    effort: "null"
    priority: "high"
  - id: "feat_epic_1755034797_22415"
    name: "null"
    effort: "null"
    priority: "null"
  - id: "feat_epic_1755034797_22841"
    name: "null"
    effort: "null"
    priority: "null"
  - id: "feat_epic_1755034797_23266"
    name: "null"
    effort: "null"
    priority: "null"
  - id: "feat_epic_1755034797_23691"
    name: ""
    effort: ""
    priority: ""
  - id: "feat_epic_1755034797_11822"
    name: "null"
    effort: "null"
    priority: "null"
  - id: "feat_epic_1755034797_12247"
    name: ""
    effort: ""
    priority: ""
  - id: "feat_epic_1755034797_12672"
    name: "null"
    effort: "null"
    priority: "null"
  - id: "feat_epic_1755034797_13098"
    name: "null"
    effort: "null"
    priority: "null"
  - id: "feat_epic_1755034797_14431"
    name: "null"
    effort: "null"
    priority: "null"
  - id: "feat_epic_1755034797_14857"
    name: ""
    effort: ""
    priority: ""
  - id: "feat_epic_1755034797_01170"
    name: "null"
    effort: "null"
    priority: "null"
  - id: "feat_epic_1755034797_07955"
    name: "null"
    effort: "null"
    priority: "null"
  - id: "feat_epic_1755034797_11106"
    name: "null"
    effort: "null"
    priority: "null"
