artifact_location: file:///Users/vitaliiserbyn/development/wt-a2-genai/champion_rigorous_testing/201459822899444288
creation_time: 1755362358323
experiment_id: '201459822899444288'
last_update_time: 1755362358323
lifecycle_stage: active
name: champion_validation_rigorous
