"""Fix business_value column to use TEXT type

Revision ID: 002_fix_business_value
Revises: 001_add_pr_achievement_tables  
Create Date: 2025-01-30 10:00:00.000000

This migration fixes the business_value column to use TEXT type instead of VARCHAR(255)
to accommodate large JSON values generated by the AI business value analyzer.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002_fix_business_value'
down_revision: Union[str, None] = '001_add_pr_achievement_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Change business_value from VARCHAR(255) to TEXT"""
    # Alter the column type to TEXT
    op.alter_column('achievements', 'business_value',
                    type_=sa.Text(),
                    existing_type=sa.String(255),
                    existing_nullable=True,
                    postgresql_using='business_value::text')


def downgrade() -> None:
    """Revert business_value back to VARCHAR(255)"""
    # First truncate any values that are too long
    op.execute("""
        UPDATE achievements 
        SET business_value = LEFT(business_value, 255)
        WHERE LENGTH(business_value) > 255
    """)
    
    # Then alter the column back
    op.alter_column('achievements', 'business_value',
                    type_=sa.String(255),
                    existing_type=sa.Text(),
                    existing_nullable=True)