artifact_uri: file:///Users/vitaliiserbyn/development/wt-a2-genai/enhanced_business_mlflow/148605544799192488/6298fba76a3e4fedb8bc080fd92ea4e6/artifacts
end_time: 1755363459090
entry_point_name: ''
experiment_id: '148605544799192488'
lifecycle_stage: active
run_id: 6298fba76a3e4fedb8bc080fd92ea4e6
run_name: tinyllama_rigorous_rigorous_20250816_195711
source_name: ''
source_type: 4
source_version: ''
start_time: 1755363431974
status: 3
tags: []
user_id: vitaliiserbyn
