artifact_location: file:///Users/vitaliiserbyn/development/wt-a2-genai/enhanced_business_mlflow/0
creation_time: 1755274472330
experiment_id: '0'
last_update_time: 1755274472330
lifecycle_stage: active
name: Default
