artifact_uri: file:///Users/vitaliiserbyn/development/wt-a2-genai/enhanced_business_mlflow/877356310361965032/f8a03c01ee3143deab923a2c2baa50a9/artifacts
end_time: null
entry_point_name: ''
experiment_id: '877356310361965032'
lifecycle_stage: active
run_id: f8a03c01ee3143deab923a2c2baa50a9
run_name: business_opt_2_7b_20250816_005502
source_name: ''
source_type: 4
source_version: ''
start_time: 1755294902236
status: 1
tags: []
user_id: vitaliiserbyn
