artifact_location: file:///Users/vitaliiserbyn/development/wt-a2-genai/champion_rigorous_testing/0
creation_time: 1755362358319
experiment_id: '0'
last_update_time: 1755362358319
lifecycle_stage: active
name: Default
