artifact_location: file:///Users/vitaliiserbyn/development/wt-a2-genai/unified_model_comparison/0
creation_time: 1755271932354
experiment_id: '0'
last_update_time: 1755271932354
lifecycle_stage: active
name: Default
