artifact_location: file:///Users/vitaliiserbyn/development/wt-a2-genai/enterprise_grade_mlflow/0
creation_time: 1755355596617
experiment_id: '0'
last_update_time: 1755355596617
lifecycle_stage: active
name: Default
