artifact_uri: file:///Users/vitaliiserbyn/development/wt-a2-genai/enhanced_business_mlflow/148605544799192488/7f12424472dd4af1a5d3db660eda65b5/artifacts
end_time: 1755425912252
entry_point_name: ''
experiment_id: '148605544799192488'
lifecycle_stage: active
run_id: 7f12424472dd4af1a5d3db660eda65b5
run_name: final_validation_bloom_560m_final_131810
source_name: ''
source_type: 4
source_version: ''
start_time: 1755425890782
status: 3
tags: []
user_id: vitaliiserbyn
