artifact_location: file:///Users/vitaliiserbyn/development/wt-a2-genai/enhanced_business_mlflow/877356310361965032
creation_time: 1755274472333
experiment_id: '877356310361965032'
last_update_time: 1755274472333
lifecycle_stage: active
name: complete_solopreneur_analysis
