artifact_uri: file:///Users/vitaliiserbyn/development/wt-a2-genai/enhanced_business_mlflow/148605544799192488/aa9f26a9191c447fa2664c4cd0455a16/artifacts
end_time: 1755425927387
entry_point_name: ''
experiment_id: '148605544799192488'
lifecycle_stage: active
run_id: aa9f26a9191c447fa2664c4cd0455a16
run_name: final_validation_tinyllama_final_131832
source_name: ''
source_type: 4
source_version: ''
start_time: 1755425912253
status: 3
tags: []
user_id: vitaliiserbyn
