artifact_uri: file:///Users/vitaliiserbyn/development/wt-a2-genai/enhanced_business_mlflow/877356310361965032/898e3185c0c641138fd77be72cbaa17b/artifacts
end_time: null
entry_point_name: ''
experiment_id: '877356310361965032'
lifecycle_stage: active
run_id: 898e3185c0c641138fd77be72cbaa17b
run_name: manual_bloom_3b_champion_20250816_150507
source_name: ''
source_type: 4
source_version: ''
start_time: 1755345907470
status: 1
tags: []
user_id: vitaliiserbyn
