artifact_location: file:///Users/vitaliiserbyn/development/wt-a2-genai/business_mlruns/0
creation_time: 1755267160383
experiment_id: '0'
last_update_time: 1755267160383
lifecycle_stage: active
name: Default
