artifact_uri: file:///Users/vitaliiserbyn/development/wt-a2-genai/enhanced_business_mlflow/877356310361965032/b3ea0f3521a24eea9ca3f1c10b4a7205/artifacts
end_time: 1755274556848
entry_point_name: ''
experiment_id: '877356310361965032'
lifecycle_stage: active
run_id: b3ea0f3521a24eea9ca3f1c10b4a7205
run_name: enhanced_solopreneur_decision_matrix
source_name: ''
source_type: 4
source_version: ''
start_time: 1755274556842
status: 3
tags: []
user_id: vitaliiserbyn
