artifact_location: file:///Users/vitaliiserbyn/development/wt-a2-genai/business_mlruns/788306403809758841
creation_time: 1755267283706
experiment_id: '788306403809758841'
last_update_time: 1755267283706
lifecycle_stage: active
name: apple_silicon_business_analysis
