id: "epic_{timestamp}"
name: "{EPIC_NAME}"
description: "{EPIC_DESCRIPTION}"
complexity: "{COMPLEXITY}"  # small, medium, large, xl
created: "{CREATED_DATE}"
status: "planning"  # planning, active, completed, on_hold
lifecycle_stage: "inception"  # inception, elaboration, construction, transition

# Epic Analysis
estimated_effort: "{EFFORT_ESTIMATE}"  # e.g., "4-8 weeks"
risk_level: "{RISK_LEVEL}"  # low, medium, high
dependencies: []  # List of epic IDs this depends on

# Feature Breakdown
features:
  - id: "feat_{epic_id}_{random}"
    name: "{FEATURE_NAME}"
    effort: "{EFFORT}"  # small, medium, large
    priority: "{PRIORITY}"  # low, medium, high

# Milestones
milestones:
  - name: "{MILESTONE_NAME}"
    target_date: "{TARGET_DATE}"
    criteria:
      - "{ACCEPTANCE_CRITERION}"

# Automation Configuration
automation:
  project_board: "local"
  branch_prefix: "{BRANCH_PREFIX}"
  ci_pipeline: "full"
  notifications:
    - channel: "development"
      events: ["milestone_reached", "blocker_detected"]

# Success Metrics
metrics:
  - name: "{METRIC_NAME}"
    target: "{TARGET_VALUE}"
    measurement: "{HOW_TO_MEASURE}"

# Notes
notes: |
  Additional context and implementation notes go here.
