name: Auto-Update Agent Focus

on:
  schedule:
    # Daily at 9 AM and 6 PM (your typical work hours)
    - cron: '0 9 * * *'   # 9 AM UTC
    - cron: '0 18 * * *'  # 6 PM UTC
  
  workflow_dispatch:
    inputs:
      agent_id:
        description: 'Agent ID to update focus for'
        required: false
        default: 'main-dev'
  
  # Auto-update on significant activity
  push:
    branches: [main, 'feat/*', 'fix/*']
    paths-ignore:
      - 'AGENT_FOCUS.md'
      - '.ai-context.json'

jobs:
  update-agent-focus:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-focus]')"
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 10  # Get recent commit history

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y bc jq

      - name: Update agent focus
        env:
          AGENT_ID: ${{ inputs.agent_id || 'main-dev' }}
        run: |
          chmod +x scripts/auto-update-agent-focus.sh
          ./scripts/auto-update-agent-focus.sh

      - name: Check for changes
        id: check-changes
        run: |
          git add AGENT_FOCUS.md
          if git diff --staged --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit updated focus
        if: steps.check-changes.outputs.changed == 'true'
        run: |
          git config --local user.email "focus-bot@threads-agent.com"
          git config --local user.name "Agent Focus Bot"
          
          # Get smart commit message based on changes
          quality_issues=$(ruff check . --quiet 2>/dev/null | wc -l || echo "0")
          commits_today=$(git log --since="$(date +%Y-%m-%d) 00:00:00" --oneline | wc -l)
          
          git commit -m "feat: auto-update agent focus based on development activity

          📊 Daily Analysis:
          - Commits today: $commits_today
          - Quality issues: $quality_issues
          - Branch: $(git branch --show-current)
          - Workflow: ${{ github.workflow }}

          🤖 Smart update based on actual development patterns
          Auto-generated: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"

          git push origin ${{ github.ref_name }}

      - name: Update AI context
        if: steps.check-changes.outputs.changed == 'true'
        env:
          AGENT_ID: ${{ inputs.agent_id || 'main-dev' }}
        run: |
          chmod +x scripts/ai-dev-acceleration.sh
          ./scripts/ai-dev-acceleration.sh context
          
          # Commit updated context
          git add .ai-context.json
          git commit -m "chore: update AI context with latest agent focus

          🧠 Context refreshed with updated focus areas
          Session: $(date +%s)
          Agent: $AGENT_ID" || echo "No context changes to commit"
          
          git push origin ${{ github.ref_name }} || echo "No changes to push"