# .github/workflows/docker-ci.yml
# Only runs when Docker-related files change
name: docker-ci

on:
  pull_request:
    paths:
      - 'services/**/Dockerfile'
      - 'services/**/requirements.txt'
      - 'services/**/*.py'
      - 'docker-compose*.yml'
      - '.github/workflows/docker-ci.yml'

jobs:
  detect-changes:
    name: Detect Changed Services
    runs-on: ubuntu-latest  # Faster startup
    timeout-minutes: 2  # Added timeout for safety
    permissions:
      contents: read
      pull-requests: read
    outputs:
      services: ${{ steps.changes.outputs.services }}
      any_changed: ${{ steps.changes.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow clone for speed

      - name: Detect service changes
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            orchestrator:
              - 'services/orchestrator/**'
            celery_worker:
              - 'services/celery_worker/**'
            persona_runtime:
              - 'services/persona_runtime/**'
            fake_threads:
              - 'services/fake_threads/**'
            viral_engine:
              - 'services/viral_engine/**'
            revenue:
              - 'services/revenue/**'
            performance_monitor:
              - 'services/performance_monitor/**'
            viral_metrics:
              - 'services/viral_metrics/**'

      - name: Set outputs
        id: set-matrix
        run: |
          services=()
          if [ "${{ steps.changes.outputs.orchestrator }}" == "true" ]; then services+=("orchestrator"); fi
          if [ "${{ steps.changes.outputs.celery_worker }}" == "true" ]; then services+=("celery_worker"); fi
          if [ "${{ steps.changes.outputs.persona_runtime }}" == "true" ]; then services+=("persona_runtime"); fi
          if [ "${{ steps.changes.outputs.fake_threads }}" == "true" ]; then services+=("fake_threads"); fi
          if [ "${{ steps.changes.outputs.viral_engine }}" == "true" ]; then services+=("viral_engine"); fi
          if [ "${{ steps.changes.outputs.revenue }}" == "true" ]; then services+=("revenue"); fi
          if [ "${{ steps.changes.outputs.performance_monitor }}" == "true" ]; then services+=("performance_monitor"); fi
          if [ "${{ steps.changes.outputs.viral_metrics }}" == "true" ]; then services+=("viral_metrics"); fi

          if [ ${#services[@]} -eq 0 ]; then
            echo "services=[]" >> $GITHUB_OUTPUT
            echo "any_changed=false" >> $GITHUB_OUTPUT
          else
            # Create compact JSON array
            json=$(printf '%s\n' "${services[@]}" | jq -R . | jq -s -c .)
            echo "services=$json" >> $GITHUB_OUTPUT
            echo "any_changed=true" >> $GITHUB_OUTPUT
          fi

  build:
    name: Build ${{ matrix.service }}
    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true'
    runs-on: ubuntu-latest  # Faster startup
    timeout-minutes: 8  # Reduced from 10 minutes
    strategy:
      fail-fast: false  # Allow parallel builds to continue
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.services) }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow clone for speed

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:latest
            network=host

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.service }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-

      - name: Build and push (optimized)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: services/${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64  # Single platform for speed
          # OPTIMIZATION: Enhanced caching strategy
          cache-from: |
            type=registry,ref=ghcr.io/${{ github.repository }}/${{ matrix.service }}:buildcache
            type=registry,ref=ghcr.io/${{ github.repository }}/${{ matrix.service }}:main
            type=registry,ref=ghcr.io/${{ github.repository }}/${{ matrix.service }}:latest
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/${{ matrix.service }}:buildcache,mode=max
          # OPTIMIZATION: Inline caching for faster builds
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Output image info (concise)
        run: |
          echo "✅ Built: ${{ steps.meta.outputs.tags }}"

  docker-summary:
    name: Docker CI Summary
    needs: [detect-changes, build]
    runs-on: ubuntu-22.04
    if: always()
    steps:
      - name: Summary
        run: |
          if [ "${{ needs.detect-changes.outputs.any_changed }}" == "false" ]; then
            echo "✅ No Docker changes detected - skipping builds"
          elif [ "${{ needs.build.result }}" == "success" ]; then
            echo "✅ All Docker images built successfully"
          elif [ "${{ needs.build.result }}" == "skipped" ]; then
            echo "✅ No Docker changes detected - builds were skipped"
          else
            echo "❌ Docker build failed"
            exit 1
          fi
