name: Move Linear issue to Done on PR merge

on:
  pull_request:
    types: [closed] # fires when the PR is merged or manually closed

jobs:
  linear-done:
    if: github.event.pull_request.merged == true # only on **merged**
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Mark Linear ticket as Done
        env:
          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
        run: |
          # branch name is available as GH env
          python scripts/ci/linear_mark_done.py "$GITHUB_HEAD_REF"
